public virtual class Animal {
   
    public String name;
    public String breed;
    public Integer age;
    public String size;


    public void eat(){
        System.debug(name + ' is eating');
    }

    public void move(){
        System.debug(name + ' is moving'); 
    }



    /*
      • Create a Parent class called Animal and provide 3 child classes.
    • Each class should have:
    
        ○ Attributes:
        Name, breed, size, age
        
        ○ Actions:
        Eat()
        Move()
    
        3 additional actions special to the sub class 
  */ 



}